[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn app:app --worker-class=gthread --workers=2 --threads=2"
healthcheckPath = "/health_check"
healthcheckTimeout = 100

[env]
FLASK_ENV = "production"
SESSION_COOKIE_SECURE = "True"
IP_RATE_LIMIT = "10 per minute"
