[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --worker-class=gthread --workers=1 --threads=2"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
FLASK_ENV = "production"
SESSION_COOKIE_SECURE = "True"
IP_RATE_LIMIT = "10 per minute"
